language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: cd ndoo && coverage run --omit=*env/* manage.py test
after_success:
  - coveralls
